/**
 * Per-socket connection wiring.  Resolves the player id from the cookie,
 * registers all event handlers, and arms a disconnect grace timer that
 * either welcomes the player back on reconnect or, after the grace
 * period, fully removes them.
 */

const { v4: uuidv4 } = require('uuid');

const World = require('../world/World');
const Sessions = require('../world/Sessions');
const Disconnects = require('../world/Disconnects');
const { parseCookies } = require('../utils/cookies');

const { validatePlayerName } = require('../utils/validation');
const { registerJoinHandlers } = require('./join');
const { registerTetrominoHandlers } = require('./tetromino');
const { registerChessHandlers } = require('./chess');
const { registerDuelHandlers } = require('./duels');
const { registerStateHandlers } = require('./state');
const { registerSpectateHandlers } = require('./spectate');
const { registerLifecycleHandlers } = require('./lifecycle');
// External AI registry. Imported via `module.exports.validateApiToken`
// on the routes module rather than the router object so a circular
// import doesn't end up empty at load time.
const externalApi = require('../../routes/api');

const PLAYER_ID_COOKIE = 'tetches_player_id';
const API_TOKEN_COOKIE = 'tetches_api_token';

function createConnectionHandler(services) {
	const { io, lifecycleService, spectatorRegistry, pauseService } = services;
	if (!io) throw new Error('createConnectionHandler: io required');
	if (!lifecycleService) throw new Error('createConnectionHandler: lifecycleService required');
	if (!spectatorRegistry) throw new Error('createConnectionHandler: spectatorRegistry required');
	if (!pauseService) throw new Error('createConnectionHandler: pauseService required');

	return function handleConnection(socket) {
		let playerId;
		try {
			playerId = resolvePlayerIdForSocket(socket, services);
		} catch (err) {
			// `resolvePlayerIdForSocket` throws on auth_token failure
			// after disconnecting the socket. Nothing more to do.
			return;
		}
		Sessions.bind(socket, playerId);

		socket.emit('player_id', playerId);
		socket.emit('set_session', { playerId });

		const handlerCtx = { ...services, playerId, socket };

		registerJoinHandlers(socket, handlerCtx);
		registerTetrominoHandlers(socket, handlerCtx);
		registerChessHandlers(socket, handlerCtx);
		registerDuelHandlers(socket, handlerCtx);
		registerStateHandlers(socket, handlerCtx);
		registerSpectateHandlers(socket, handlerCtx);
		registerLifecycleHandlers(socket, handlerCtx);

		socket.on('disconnect', () => {
			handleDisconnect(socket, playerId, services);
		});
	};
}

function handshakePlayerName(socket) {
	const raw = socket.handshake?.query?.playerName;
	return validatePlayerName(raw);
}

function isAutoGeneratedPlayerName(name) {
	if (!name || typeof name !== 'string') return true;
	return /^Player_[a-f0-9]{6}$/i.test(name.trim())
		|| /^DevPlayer_/i.test(name.trim());
}

/**
 * Pull a {playerId, apiToken} pair out of the handshake. We accept
 * either the query string (`?playerId=…&apiToken=…`) or cookies
 * (`tetches_player_id=…; tetches_api_token=…`). Both are read-only
 * lookups so it doesn't matter which the bot uses.
 */
function readRegisteredBotCredentials(socket, cookies) {
	const query = socket.handshake?.query || {};
	const playerId = (query.playerId && String(query.playerId).trim())
		|| cookies[PLAYER_ID_COOKIE]
		|| null;
	const apiToken = (query.apiToken && String(query.apiToken).trim())
		|| cookies[API_TOKEN_COOKIE]
		|| null;
	return { playerId, apiToken };
}

function resolvePlayerIdForSocket(socket, services) {
	const { lifecycleService } = services;
	const cookies = parseCookies(socket.handshake.headers.cookie);
	const handshakeName = handshakePlayerName(socket);

	// Registered external-AI path: if the bot presents the playerId
	// + apiToken they got from `POST /api/computer-players/register`,
	// claim that identity even if no World record exists yet (or one
	// was wiped by the disconnect-grace sweep). Token validation is
	// the only place an external bot is auth'd; once authed they
	// behave exactly like any other socket player.
	const creds = readRegisteredBotCredentials(socket, cookies);
	if (creds.apiToken
		&& creds.playerId
		&& typeof externalApi.validateApiToken === 'function'
		&& externalApi.validateApiToken(creds.playerId, creds.apiToken)) {
		const botId = creds.playerId;
		Disconnects.clear(botId);
		const record = World.getPlayer(botId);
		const desiredName = (handshakeName && handshakeName.toLowerCase() !== 'guest')
			? handshakeName
			: (record?.name || `Bot_${botId.slice(-6)}`);
		if (!record) {
			console.log(`External AI re-binding identity ${botId} (no prior record; recreating)`);
			World.upsertPlayer(botId, {
				name: desiredName,
				isComputer: true,
				external: true,
				lastActiveAt: Date.now(),
			});
		} else {
			console.log(`External AI ${botId} connecting (socket ${socket.id})`);
			record.lastActiveAt = Date.now();
			record.isComputer = true;
			record.external = true;
			if (handshakeName
				&& handshakeName.toLowerCase() !== 'guest'
				&& isAutoGeneratedPlayerName(record.name)) {
				record.name = handshakeName;
			}
			World.markDirty();
		}
		socket.join(World.getWorldId());
		return botId;
	}

	// Reject a query-string token that didn't match. A *missing*
	// token is fine (regular browser join); a *wrong* one is most
	// likely a bot misconfigured against the wrong server.
	if (creds.apiToken && !externalApi.validateApiToken?.(creds.playerId, creds.apiToken)) {
		console.warn(`External AI auth failed for playerId=${creds.playerId} (socket ${socket.id})`);
		socket.emit('auth_error', { reason: 'invalid_api_token' });
		try { socket.disconnect(true); } catch (_e) { /* socket already closing */ }
		// Fall through to a throw so callers don't accidentally use
		// an unauthenticated identity.
		throw new Error('invalid_api_token');
	}

	let playerId = cookies[PLAYER_ID_COOKIE];
	const existingRecord = playerId ? World.getPlayer(playerId) : null;
	const wasEliminated = !!existingRecord?.eliminated;

	if (existingRecord && !wasEliminated) {
		console.log(`Player reconnecting: ${playerId} (socket ${socket.id})`);
		Disconnects.clear(playerId);
		existingRecord.lastActiveAt = Date.now();
		if (handshakeName
			&& handshakeName.toLowerCase() !== 'guest'
			&& isAutoGeneratedPlayerName(existingRecord.name)) {
			existingRecord.name = handshakeName;
		}
		World.markDirty();
		socket.join(World.getWorldId());
		return playerId;
	}

	if (existingRecord && wasEliminated) {
		console.log(`Eliminated player ${playerId} refreshed; issuing a fresh player identity.`);
		Disconnects.clear(playerId);
		lifecycleService.removePlayerCompletely(playerId);
	}

	const freshId = uuidv4();
	console.log(`New player connected: ${freshId} (socket ${socket.id})`);
	const initialName = (handshakeName && handshakeName.toLowerCase() !== 'guest')
		? handshakeName
		: `Player_${freshId.substring(0, 6)}`;
	World.upsertPlayer(freshId, {
		name: initialName,
		lastActiveAt: Date.now(),
	});
	return freshId;
}

function handleDisconnect(socket, playerId, services) {
	const { lifecycleService, spectatorRegistry } = services;
	console.log(`Player disconnected: ${playerId} (grace period ${Disconnects.DEFAULT_GRACE_MS / 1000}s)`);

	Sessions.unbind(socket.id);
	spectatorRegistry.stop(playerId);

	if (World.getPlayer(playerId)) {
		Disconnects.arm(playerId, () => {
			console.log(`Grace period expired for ${playerId}, removing from world`);
			lifecycleService.removePlayerCompletely(playerId);
		});
	} else {
		lifecycleService.removePlayerCompletely(playerId);
	}
}

module.exports = { createConnectionHandler, PLAYER_ID_COOKIE };
